name: Build and Release WinForms/WPF App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Standalone winform Executable
      run: |
        dotnet publish src/BlazorWinFormsApp/IFCjsWinFormsApp.csproj -c Release -r win-x64 -o ./output/winform

    - name: Create Standalone wpf Executable
      run: |
        dotnet publish src/BlazorWpfApp/IFCjsWpfApp.csproj -c Release -r win-x64 -o ./output/Wpf
        
    - name: Zip winform Artifacts
      run: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory('./output/winform', 'WinFormsApp.zip')

    - name: Zip wpf Artifacts
      run: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory('./output/Wpf', 'WpfApp.zip')
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Changes in this release.

    - name: Upload Release Asset
      id: upload-winform-release-asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token    
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./WinFormsApp.zip
        asset_name: WinFormsApp.zip
        asset_content_type: application/zip

    - name: Upload wpf Release Asset
      id: upload-wpf-release-asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token    
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./WpfApp.zip
        asset_name: WpfApp.zip
        asset_content_type: application/zip
